services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: Test
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: fastapi-backend
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGODB_URL: mongodb://mongo:27017
      DATABASE_NAME: Test
    volumes:
      - .:/app


volumes:
  mongo_data:
